---
branches:
  only:
    - 2.x.x
    - /^\d+\.\d+\.\d+$/

jobs:
  fast_finish: true

  include:
    - &Test

      name: Ubuntu 16.04 / Ansible 2.8 / Solr 7.7.2

      os: linux

      dist: xenial

      cache:
        pip: true

      language: python

      python: 3.6

      env: MOLECULE_PLATFORM=ubuntu:18.04 ANSIBLE_VERSION=2.8.* SOLR_VERSION=7.7.2

      install:
        - pip install ansible==${ANSIBLE_VERSION} ansible-lint docker molecule==3.*

      script:
        - molecule test

    - <<: *Test

      name: Ubuntu 18.04 / Ansible 2.9 / Solr 8.4.1

      env: MOLECULE_PLATFORM=ubuntu:18.04 ANSIBLE_VERSION=2.9.* SOLR_VERSION=8.4.1

    - <<: *Test

      name: Ubuntu 20.04 / Ansible 2.9 / Solr 8.5.1

      env: MOLECULE_PLATFORM=ubuntu:20.04 ANSIBLE_VERSION=2.9.* SOLR_VERSION=8.5.1

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
