---
jobs:
  fast_finish: true

  include:
    - &Test

      os: linux

      dist: xenial

      cache:
        pip: true

      language: python

      python: 3.6

      env: MOLECULE_PLATFORM=ubuntu:16.04 ANSIBLE_VERSION=2.7.*

      install:
        - pip install ansible==${ANSIBLE_VERSION} docker molecule

      script:
        - molecule test

    - <<: *Test

      env: MOLECULE_PLATFORM=ubuntu:18.04 ANSIBLE_VERSION=2.7.*

    - <<: *Test

      env: MOLECULE_PLATFORM=ubuntu:16.04 ANSIBLE_VERSION=2.8.*

    - <<: *Test

      env: MOLECULE_PLATFORM=ubuntu:16.04 ANSIBLE_VERSION=2.9.*

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
