---
- name: Ensure Solr conf directories exist
  file:
    path: '{{ solr_data_dir }}/data/{{ item.name }}/conf'
    state: directory
    owner: '{{ solr_user }}'
    group: '{{ solr_group }}'
    recurse: true
  loop: '{{ solr_cores }}'

- name: Set default core configuration path
  set_fact:
    # yamllint disable-line rule:line-length
    solr_default_core_conf_path: '{{ solr_install_dir }}/solr/example/files/conf'

- name: Copy configuration for all defined cores
  synchronize:
    src: '{{ item.conf_path | default(solr_default_core_conf_path) }}/'
    dest: '{{ solr_data_dir }}/data/{{ item.name }}/conf/'
    checksum: true
    delete: true
    times: false
  loop: '{{ solr_cores }}'
  register: solr_cores_configuration_sync
  become: true
  become_user: '{{ solr_user }}'
  delegate_to: '{{ inventory_hostname }}'

- name: Get status of every defined core
  uri:
    # yamllint disable-line rule:line-length
    url: http://localhost:{{ solr_port }}/solr/admin/cores?action=STATUS&indexInfo=false&core={{ item.name }}
    return_content: true
  loop: '{{ solr_cores }}'
  register: solr_cores_status_api_response

- name: Parse cores status API response
  xml:
    xmlstring: '{{ solr_cores_status_api_response.results[index].content }}'
    xpath: /response/lst[@name="status"]/lst[@name]/str[@name="name"]
    count: true
  loop: '{{ solr_cores }}'
  loop_control:
    index_var: index
  register: solr_cores_status

- name: Create defined cores unless they exist already
  command: '{{ solr_install_dir }}/solr/bin/solr create -c {{ item.name }}'
  when: solr_cores_status.results[index].count == 0
  loop: '{{ solr_cores }}'
  loop_control:
    index_var: index
  become: true
  become_user: '{{ solr_user }}'

- name: Reload cores if their configuration has been changed
  uri:
    # yamllint disable-line rule:line-length
    url: http://localhost:{{ solr_port }}/solr/admin/cores?action=RELOAD&core={{ item.name }}
  loop: '{{ solr_cores }}'
  loop_control:
    index_var: index
  when: solr_cores_configuration_sync.results[index].changed
