---
- name: Ensure Solr conf directories exist
  file:
    path: '{{ solr_data_dir }}/data/{{ item }}/conf'
    state: directory
    owner: '{{ solr_user }}'
    group: '{{ solr_group }}'
    recurse: true
  loop: '{{ solr_cores }}'

- name: Copy default configuration for all cores
  command: 'cp -R {{ solr_install_dir }}/solr/example/files/conf/ {{ solr_data_dir }}/data/{{ item }}/'
  args:
    creates: '{{ solr_data_dir }}/data/{{ item }}/conf/solrconfig.xml'
  loop: '{{ solr_cores }}'
  register: solr_cores_configuration
  become: yes
  become_user: '{{ solr_user }}'

- name: Create configured cores
  command: '{{ solr_install_dir }}/solr/bin/solr create -c {{ item }}'
  when: "'skipped' not in solr_cores_configuration.results[index].stdout"
  loop: '{{ solr_cores }}'
  loop_control:
    index_var: index
  become: yes
  become_user: '{{ solr_user }}'
