---
# Ensure base packages are present.
- name: Install base packages
  apt:
    name:
      - curl
      - gnupg2
      - lsof
      - rsync
      - sed
      - tar
    state: present
    update_cache: true
    cache_valid_time: 86400

- name: Create Solr user and group
  include_tasks: user.yml

- name: Install Solr
  include_tasks: install.yml

- name: Configure Solr cores
  include_tasks: cores.yml

- name: Clean up
  include_tasks: cleanup.yml
  when: solr_existing_version is failed
