---
# Ensure base packages are present.
- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - curl
    - gnupg2
    - lsof

# Create Solr user and group.
- include: user.yml

# Install Solr.
- include: install.yml

# Configure Solr cores.
- include: cores.yml

# Clean up.
- include: cleanup.yml
  when: solr_existing_version|failed
