---

- name: Make solr group exists
  group:
    name: "{{ solr_user_group }}"
    state: present

- name: Make sure solr user exists
  user:
    name: "{{ solr_user }}"
    state: present
    group: "{{ solr_user_group }}"
