---
# Create Solr group if doesn't exist.
- name: Make sure solr group exists
  group:
    name: "{{ solr_group }}"
    state: present

# Create Solr user if doesn't exist.
- name: Make sure solr user exists
  user:
    name: "{{ solr_user }}"
    state: present
    group: "{{ solr_group }}"
