---
- name: Reload cores if their configuration has been changed
  uri:
    # yamllint disable-line rule:line-length
    url: http://localhost:{{ solr_port }}/solr/admin/cores?action=RELOAD&core={{ item.name }}
  loop: '{{ solr_cores }}'
  loop_control:
    index_var: index
  when: solr_cores_configuration_sync.results[index].changed
