---
- hosts: all
  become: true

  pre_tasks:

    - name: Ensure Ansible temp directory exists
      file:
        path: /tmp/ansible
        state: directory
        mode: 0777

    - name: Ensure base packages are installed
      apt:
        name:
          - libxml2-dev
          - libxslt-dev
          - python3-dev
          - python3-lxml
          - rsync
        state: present
        update_cache: true

  roles:
    - t2l.java
    - t2l.solr

  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Older Solr versions might not work properly with OpenJDK 11. Let's stick
    # to the JDK 8.
    java_openjdk_packages:
      - version: 8
        type: jre
    java_default_alternative:
      provider: openjdk
      version: 8

    # Solr cores to configure.
    solr_cores:
      - name: drupal
      - name: wordpress
        conf_path: /opt/solr/example/files/conf
