---
- hosts: all
  become: true

  pre_tasks:

    - name: Ensure Ansible temp directory exists
      file:
        path: /tmp/ansible
        state: directory
        mode: 0777

    - name: Ensure base packages are installed
      apt:
        name:
          - libxml2-dev
          - libxslt-dev
          - python-dev
          - python-lxml
          - rsync
        state: present
        update_cache: true
        cache_valid_time: 86400

  roles:
    - T2L.java
    - ansible-role-solr

  vars:
    # Older Solr versions might not work properly with OpenJDK 11. Let's stick
    # to the JDK 8.
    java_openjdk_packages:
      - version: 8
        type: jre
    java_default_alternative:
      provider: openjdk
      version: 8

    # Do not remove downloads in order to pass idempotence tests.
    solr_cleanup_downloads: false
    solr_cleanup_gpg: false

    # Solr cores to configure.
    solr_cores:
      - name: drupal
      - name: wordpress
        conf_path: /opt/solr/example/files/conf
